### ISSUE TITLE
Can't access admin area

### ISSUE THREAD

**Issue by sabja** [frapid/frapid#29]
hi,

I can't access the admin area because i can't receive the verification account.

i have create an account in Sendgrid, but the problem is that i don't know realy what to put in the Enter from email section in the config file.

also there is no configuration to make in sendgrid settings ??

thank you for reply.

**Comment by mixerp** [comment]
hello, you can register first using the email address configured as admin. If you cannot configure sendgrid, manually insert the data from account.registrations table to account.users table.

**Comment by aswanee** [comment]
hi,
Dear MixERP
i have logged the message send by email at SendGridMail in class Processor (email.Message)
and confirmed the account 
but whin try to loin in admin area
get this error :
**Cannot invoke a non-delegate type
2017-05-16 10:21:54.881 +02:00 [Information] Application started.
2017-05-16 10:21:54.903 +02:00 [Information] Registering Web API.
2017-05-16 10:33:34.825 +02:00 [Error] Invalid antiforgery cookie data.
IP: "::1"
Browser: "Chrome"
User Agener: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36". Stack: "System.Web.Mvc.HttpAntiForgeryException (0x80004005): The required anti-forgery form field \"__RequestVerificationToken\" is not present.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext, String cookieToken, String formToken)
   at Frapid.Areas.CSRF.AntiForgeryAttribute.OnAuthorization(AuthorizationContext filterContext) in C:\ERP\Frapid\src\Libraries\Frapid.Areas\CSRF\AntiForgeryAttribute.cs:line 28"
2017-05-16 10:33:36.827 +02:00 [Warning] Invalid login claims supplied. Access was denied to user 0/null for officeId 0 having the loginId 0. Token: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGcmFwaWQiLCJpYXQiOiI2MzYzMDUxNzc1Mzc4NDMzNTIiLCJleHAiOiI2MzYzMDYwNDE1Mzc4NDMzNTIiLCJzdWIiOiJsb2NhbGhvc3QiLCJsb2dpbmlkIjoiMSJ9.LvOGixjhyQZKIax6GXw_4kjX-Di8YuJIf07MtQ3hTMUcVkkn8HHhcFdYe89GUu51M6YMdMa836EmMxwYwZIukA".**

**Comment by aswanee** [comment]
hi 
the Cannot invoke a non-delegate type
generate new Error 

I have loge in by chrome incognito page  
the login success but when refresh dashboard all icons disappeared and the loge register this error :
2017-05-16 11:04:09.022 +02:00 [Information] Application started.
2017-05-16 11:04:09.043 +02:00 [Information] Registering Web API.
2017-05-16 11:04:37.735 +02:00 [Error] Invalid antiforgery cookie data.
IP: "::1"
Browser: "Chrome"
User Agener: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36". Stack: "System.Web.Mvc.HttpAntiForgeryException (0x80004005): The required anti-forgery form field \"__RequestVerificationToken\" is not present.
   at System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken)
   at System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext, String cookieToken, String formToken)
   at Frapid.Areas.CSRF.AntiForgeryAttribute.OnAuthorization(AuthorizationContext filterContext) in C:\ERP\Frapid\src\Libraries\Frapid.Areas\CSRF\AntiForgeryAttribute.cs:line 28"
2017-05-16 11:04:45.526 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:04:45.631 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:04:45.714 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:06:28.696 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:06:28.733 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:06:28.883 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:07:24.378 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:07:24.454 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:07:24.536 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:09:43.615 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
2017-05-16 11:09:56.171 +02:00 [Error] Exception occurred in localhost on Default. Application user: 1 (Mohamed Rashed).

Cannot invoke a non-delegate type
